- name: Ensure awscli v2 is downloaded
  ansible.builtin.unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /var/tmp/
    remote_src: true
    creates: /var/tmp/aws/install

- name: Install awscli v2 if not already installed
  ansible.builtin.command:
    cmd: /var/tmp/aws/install --update
    creates: /usr/local/bin/aws
