---
- name: Ensure scanning software is installed
  ansible.builtin.package:
    name: simple-scan

- name: Ensure mouse configuration software is installed
  ansible.builtin.package:
    name: piper

- name: Ensure chrome is installed
  ansible.builtin.package:
    name: google-chrome-stable
