---
- name: Ensure scanning software is installed
  ansible.builtin.package:
    name: simple-scan

- name: Ensure mouse configuration software is installed
  ansible.builtin.package:
    name: piper

- name: Ensure chrome is installed
  ansible.builtin.package:
    name: google-chrome-stable

- name: Ensure zoom-us repository key is installed
  ansible.builtin.rpm_key:
    key: https://zoom.us/linux/download/pubkey?version=6-3-10
    fingerprint: AE44 6BAB 33EA 9862 AA29 FC3D DDE0 E622 2047 091F
    state: present

- name: Ensure zoom is installed
  ansible.builtin.package:
    # name: https://zoom.us/client/latest/zoom_x86_64.rpm
    name: https://zoom.us/client/6.5.3.2773/zoom_x86_64.rpm
    state: present
