---
- name: Ensure the tailscale repository is configured
  block:
    - name: Ensure tailscale repository key is installed
      ansible.builtin.rpm_key:
        key: https://pkgs.tailscale.com/stable/fedora/repo.gpg
        state: present

    - name: Ensure tailscale repository is enabled
      ansible.builtin.yum_repository:
        name: tailscale-stable
        description: Tailscale stable
        baseurl: https://pkgs.tailscale.com/stable/fedora/$basearch/
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg

- name: Ensure tailscale is installed
  ansible.builtin.package:
    name: tailscale
    state: present
  notify: Additional install instructions

- name: Ensure tailscald is started and enabled
  ansible.builtin.service:
    name: tailscaled.service
    state: started
    enabled: true
