---
- name: Ensure prerequisites
  block:
    - name: Ensure fontconfigs is installed
      ansible.builtin.package:
        name: fontconfig
        state: installed

    - name: Ensure decompression tools are installed
      ansible.builtin.package:
        name:
          - xz
          - unzip
        state: installed

- name: Download and extract fonts
  ansible.builtin.include_tasks: ./download_extract_fonts.yml
  loop: "{{ fonts }}"
  loop_control:
    loop_var: font
