---
- name: Ensure wheel group can edit {{ playbook_path }}
  ansible.builtin.file:
    path: "{{ playbook_path }}"
    mode: u=rwX,g=rwX,o=rX
    owner: root
    group: wheel
    recurse: true
  changed_when: false

- name: Template ansible-pull systemd service
  ansible.builtin.template:
    src: ansible-pull.service.j2
    dest: /etc/systemd/system/ansible-pull.service
    mode: "0644"
    owner: root
    group: root

- name: Template ansible-pull systemd timer
  ansible.builtin.template:
    src: ansible-pull.timer.j2
    dest: /etc/systemd/system/ansible-pull.timer
    mode: "0644"
    owner: root
    group: root

- name: Template ansible-pull log directory
  ansible.builtin.file:
    path: /var/log/ansible-pull
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Setup log rotation for ansible-pull
  ansible.builtin.copy:
    content: |
      /var/log/ansible-pull/*.log {
          rotate 30
          maxage 30
          missingok
          notifempty
          nocompress
          nocreate
      }
    dest: /etc/logrotate.d/ansible-pull
    mode: "0644"
    owner: root
    group: root

# - name: Setup log rotation for ansible-pull
#   ansible.builtin.copy:
#     content: |
#       /var/log/ansible-pull/*.log {
#           daily
#           rotate 7
#           compress
#           delaycompress
#           missingok
#           notifempty
#           create 0644 root root
#       }
#     dest: /etc/logrotate.d/ansible-pull
#     mode: "0644"
#     owner: root
#     group: root

- name: Enable and start ansible-pull timer
  ansible.builtin.systemd:
    name: ansible-pull.timer
    enabled: true
    state: started
    daemon_reload: true

- name: Template ansible-pull management script
  ansible.builtin.template:
    src: ansible-pull-manage.sh.j2
    dest: /usr/local/bin/ansible-pull-manage
    mode: "0755"
    owner: root
    group: root
